# Generated by Django 2.1.2 on 2018-10-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
            },
        ),
        migrations.CreateModel(
            name='GameKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Key')),
                ('buy_date', models.DateField(verbose_name='Fecha de compra')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('minimum_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio mínimo de venta')),
                ('sell_date', models.DateField(blank=True, null=True, verbose_name='Fecha de venta')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Bundle', verbose_name='Bundle')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('access_key', models.CharField(max_length=255, verbose_name='Clave de acceso')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.AddField(
            model_name='gamekey',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Member', verbose_name='Comprador'),
        ),
        migrations.AddField(
            model_name='gamekey',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Game', verbose_name='Juego'),
        ),
        migrations.AddField(
            model_name='gamekey',
            name='sell_web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Web', verbose_name='Web de venta'),
        ),
    ]
